module.exports.SqlQuery = {

    isExistgame: "SELECT id FROM games WHERE name=?",
    addGames: "INSERT INTO games(name,description,game_url,min_players_count,max_players_count,category,image) VALUES(?,?,?,?,?,?,?)",
    editGame: "SELECT g.*, c.name as categoryName FROM games g JOIN category c on g.category=c.id WHERE g.id=?",
    listGame: "SELECT g.*, c.name as categoryName, COUNT(l.game_id) as likes FROM games g JOIN category c on g.category=c.id left join likes l on l.game_id=g.id GROUP by g.id limit ? offset ?",
    findCategory: "SELECT id, name FROM category WHERE name=?",
    filterGames: "SELECT g.*, c.name as categoryName, COUNT(l.game_id) as likes FROM games g JOIN category c on g.category=c.id left join likes l on l.game_id=g.id WHERE g.category=? GROUP BY g.id  limit ? offset ? ",
    isExistId: "SELECT id FROM games WHERE id=?",
    updateGame: "UPDATE games SET name=?, description=?, game_url=?, min_players_count=?, max_players_count=?, category=?, up_date=?, image=? WHERE id=?",
    deleteGame: "DELETE FROM games WHERE id=?",
    isExistCategory: "SELECT id FROM category WHERE name=?",
    addCategory: "INSERT INTO category(name) VALUES(?)",
    editCategory: "SELECT * FROM category WHERE id=?",
    listCategory: "SELECT * FROM category",
    isExistCategoryId: "SELECT * FROM category WHERE id=?",
    updateCategory: "UPDATE category SET name=?, up_date=? WHERE id=?",
    deleteCategory: "DELETE FROM category WHERE id=?",
    addLikes: "INSERT INTO likes (game_id, user_id) VALUES (?, ?)",
    disLike:"DELETE FROM likes WHERE game_id=? AND user_id=?",
    isExistGameUserId: "SELECT id FROM likes WHERE game_id=? AND user_id=?",
    isExistUser: "SELECT id FROM users WHERE username=?",
    isExistEmail: "SELECT id FROM users WHERE email=?",
    isExistUserId: "SELECT id FROM users WHERE id=?",
    addUsers: "INSERT INTO users(username, email, password, address) values (?,?,?,?)",
    userLogin: "SELECT * FROM users WHERE username=?",
    editUsers: "SELECT * FROM users WHERE id=?",
    listUsers: "SELECT * FROM users",
    updateUser: "UPDATE users SET username=?, email=?, password=?, address=?, up_date=? WHERE id=?",
    deleteUser: "DELETE FROM users WHERE id=?"
}